#!/usr/bin/env bash

set -eu

packages=($(grep --perl '{{.*(?<!out)}}' src/*.hs | sed -e 's|.*{{\(.*\)}}/.*|\1|' | sort -u))

extra_args=(--extra-arguments fetchgit)
for p in "${packages[@]}"; do
    extra_args+=(--extra-arguments "$p")
done

cabal2nix . "${extra_args[@]}" \
    | head -n-1

echo "  executableSystemDepends = ["
for p in "${packages[@]}"; do
    echo "    $p"
done
echo "  ];"

echo "  postPatch = ''";
for hs in src/*.hs; do
    echo "    substituteInPlace $hs \\"
    echo "      --replace '{{out}}' \"\$out\" \\"
    for p in "${packages[@]}"; do
        echo "      --replace '{{$p}}' '\${$p}' \\"
    done
    echo "    ;"
done
echo "  '';"

echo "}"
