#
# DO NOT EDIT - generated by gen-nix
#
{ mkDerivation, base, gdk-pixbuf, lib, lightlocker, sys-pulseaudio
, taffybar, unix, wrapGAppsHook, X11, xmonad, xmonad-contrib
}:
mkDerivation {
  pname = "xmonad-custom";
  version = "0.0.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    base taffybar unix X11 xmonad xmonad-contrib
  ];
  description = "My XMonad build";
  license = lib.licenses.bsd3;
  executableSystemDepends = [
    wrapGAppsHook
    gdk-pixbuf
  ];
  postPatch = ''
    substituteInPlace src/Taffybar.hs \
      --replace '{{out}}' "$out" \
      --replace '{{lightlocker}}' '${lightlocker}' \
      --replace '{{sys-pulseaudio}}' '${sys-pulseaudio}' \
    ;
    substituteInPlace src/Xmonad.hs \
      --replace '{{out}}' "$out" \
      --replace '{{lightlocker}}' '${lightlocker}' \
      --replace '{{sys-pulseaudio}}' '${sys-pulseaudio}' \
    ;
  '';
}
