# Prevent "error connecting to disability bus" messages from GTK programs
export NO_AT_BRIDGE=1

# Set VISUAL to be picked up by git commit
export VISUAL="emacsclient --alternate-editor '' --create-frame"
